volumes:
  db_data:

services:
  database:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=confab
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=confab_development
