default: &default
  adapter: postgresql
  encoding: unicode
  username: confab
  password: password
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  variables:
    statement_timeout: 5000

development:
  <<: *default
  host: localhost
  database: confab_development

test:
  <<: *default
  host: localhost
  database: confab_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  # cache:
  #   <<: *primary_production
  #   database: confab_production_cache
  #   migrations_paths: db/cache_migrate
  # queue:
  #   <<: *primary_production
  #   database: confab_production_queue
  #   migrations_paths: db/queue_migrate
  # cable:
  #   <<: *primary_production
  #   database: confab_production_cable
  #   migrations_paths: db/cable_migrate
